apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "buildachart.fullname" . }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiftsrv
  template:
    metadata:
      labels:
        app: shiftsrv
    spec:
      containers:
        - name: shiftsrv
          image: cdchathura/shiftsrv:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: db.url
              value: {{ (index .Values "db.url") }}


---

kind: Service
apiVersion: v1
metadata:
  name: {{ template "buildachart.fullname" . }}-service
spec:
  type: NodePort
  selector:
    app: shiftsrv
  ports:
    - port: 8080
      nodePort: 30000